# Generated by Django 2.1 on 2019-01-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collarNumber', models.IntegerField()),
                ('date', models.DateField(verbose_name='shift date')),
                ('startTime', models.DateTimeField(verbose_name='shift start')),
                ('endTime', models.DateTimeField(verbose_name='shift end')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
